# Generated by Django 2.1.7 on 2019-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='qr_link',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
