# Generated by Django 2.1.7 on 2019-03-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_data_qr_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
