# Generated by Django 2.1.7 on 2019-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_user_data_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
