# Generated by Django 2.1.7 on 2019-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_price_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('default_text', models.CharField(max_length=5000)),
            ],
        ),
    ]
