# Generated by Django 2.1.7 on 2019-03-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190322_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='customer_email',
            field=models.EmailField(blank=True, default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='customer_no',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
