# Generated by Django 2.1.7 on 2019-03-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_daily_cunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='daily_cunter',
            field=models.IntegerField(default=1),
        ),
    ]
