# Generated by Django 2.1.7 on 2019-03-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_user_data_daily_cunter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daily_cunter',
            new_name='daily_counter',
        ),
    ]
