# Generated by Django 2.1.7 on 2019-03-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190322_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='daily_cunter',
            new_name='daily_counter',
        ),
    ]
