def pdf(name, adult, children, total, date_time, counter):
    from reportlab.pdfgen import canvas
    canvas = canvas.Canvas("static/website/pdf/print.pdf", pagesize=(300,360))
    canvas.setLineWidth(.3)
    canvas.setFont('Helvetica', 19)
    canvas.drawInlineImage("static/website/images/butterfly.jpeg", 82,303, width=46,height=46)
    canvas.drawString(138,340,'The')
    canvas.drawString(138,322,'Butterfly')
    canvas.drawString(138,300,'Corner')
    canvas.setFont('Helvetica', 14)
    canvas.drawString(220,300,'Sr. No : ' + str(counter))
    canvas.line(10,291,290,291)
    canvas.drawInlineImage("qrcodes/qrcode.png", 72, 131, width=155,height=155)
    canvas.line(10,124,290,124)
    canvas.setFont('Helvetica', 16)
    canvas.drawString(20,100,'Total : ' + total+ ' THB')

    canvas.setFont('Helvetica', 14)
    canvas.drawString(20,80,'Date & Time : ' + date_time)
    canvas.drawString(20,60,'Name : ' + name)
    canvas.drawString(20,40,'Adult : '+adult)
    canvas.drawString(170,40,'Children : ' + children)
    canvas.save()